Update Roscon 2022 Docker
o3de/ROSConDemo pull request #267
Opened 2023-10-16 22:39 UTC by spham-amzn

Fixes and updates to the ROSConDemo from RosCon 2022 to support the latest 23.10 release. 
* Add support to use the new Project Exporter script that will create a release-build package of the project. This reduces the size of the docker image significantly when creating a docker image just to run the simulation.
* Fix a monolithic-release build issue related to the `RosconDemo` gem adding a dependency to `            Gem::AtomLyIntegration_CommonFeatures.Editor.Static` which is an editor target.
* Add a patch necessary to build the launcher in release build against release 23.10 (this will be fixed in the future)
* Perform optimization to the Dockerfile scripts to reduce the size and steps as much as possible
* Update the docker read me to describe the changes

2023-10-16 23:02 UTC, mbalfour-amzn approved these changes

2023-10-16 23:02 UTC, mbalfour-amzn commented on docker/README.md
> +This Dockerfile will build a docker container will only have the `kraken_nav` code for the navigation stack.
```suggestion
This Dockerfile will build a docker container that will only have the `kraken_nav` code for the navigation stack.
```

2023-10-17 00:29 UTC, AMZN-alexpete approved these changes

2023-10-26 08:39 UTC, jhanca-robotecai requested changes
Please fix the filepaths in _Dockerfiles_. Other than that - good to go.

2023-10-26 08:39 UTC, jhanca-robotecai commented on docker/README.md
> +source /data/workspace/kraken_nav/install/setup.bash
`kranken_nav` is located inside the repo folder in the `roscon_demo` image.
```suggestion
source /data/workspace/ROSConDemo/kraken_nav/install/setup.bash
```

2023-10-26 08:39 UTC, jhanca-robotecai commented on docker/README.md
> +  The Docker image created from this script will only havethe compiled `kraken_nav` code for the navigation stack.
```suggestion
  The Docker image created from this script will only have the compiled `kraken_nav` code for the navigation stack.
```

2023-10-26 08:39 UTC, jhanca-robotecai commented on docker/README.md
> +These images will be much smaller that the full `roscon_demo` docker image.
```suggestion
These images will be much smaller than the full `roscon_demo` docker image. 
```

2023-10-26 15:02 UTC, spham-amzn commented on docker/README.md
> +source /data/workspace/kraken_nav/install/setup.bash
This is actually the path to the copied version from the source that is pulled from git. I do this to wipe all of the git folders at the end of the RUN context to reduce the size of the container (to prevent docker from saving a context with the entire github folder). But, I can also delete around it and will remove the 'COPY' command instead and fix this

2023-10-27 08:42 UTC, jhanca-robotecai commented on docker/README.md
> +source /data/workspace/kraken_nav/install/setup.bash
I see the code in _dockerfiles_ for `roscon_sim` and `roscon_nav`. But my understanding is that this part of the `README` belongs to `roscon_demo` image, in which you rather [wipe out](https://github.com/spham-amzn/ROSConDemo/blob/3022b60e120dfdc5327f0cc5b09a2bdcd52fa757/docker/Dockerfile#L149) `.git` and multiple `build/...` folders.

2023-10-27 08:44 UTC, jhanca-robotecai commented on docker/README.md
> +source /data/workspace/kraken_nav/install/setup.bash
Quick test:

```bash
jhanca@robotec-o3de:~$ docker run -it roscon_demo
root@4e8d90223c42:/data/workspace# ls
ROSConDemo  o3de  o3de-extras  o3de_2.1.0.patch
root@4e8d90223c42:/data/workspace# ls ROSConDemo/
CODE_OF_CONDUCT.md     LICENSE-CC-BY-NC-4.0.txt  LICENSE_MIT.TXT  docker      static
CONTRIBUTING.md        LICENSE.txt               Project          docs
LICENSE-CC-BY-4.0.txt  LICENSE_APACHE2.TXT       README.md        kraken_nav
root@4e8d90223c42:/data/workspace# exit
exit
jhanca@robotec-o3de:~$ docker run -it roscon_nav
root@47fe90250fca:/data/workspace# ls
kraken_nav
root@47fe90250fca:/data/workspace# exit
exit
jhanca@robotec-o3de:~$ 
```

2023-11-02 17:14 UTC, spham-amzn commented on docker/README.md
> +source /data/workspace/kraken_nav/install/setup.bash
Ah, you are right, the `roscon_demo` based on the full editor and project image does not do wipe out. Thanks for the correction

2023-11-03 07:01 UTC, jhanca-robotecai approved these changes

2023-11-06 02:32 UTC, merged